#!/usr/bin/env python3
"""
Generate a fixed chiplab adapter for mkCoreAxiTop.

Input:
  src/build/verilog/mkCoreAxiTop.v

Output:
  chiplab/IP/myCPU/mycpu_top.v   (module name fixed: core_top)
"""

from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def require_ports(text: str, ports: list[str]) -> None:
    missing = [p for p in ports if p not in text]
    if missing:
        miss = ", ".join(missing)
        raise RuntimeError(f"mkCoreAxiTop.v missing required ports: {miss}")


def render_wrapper(enable_diffcommit: bool) -> str:
    diff_decl = ""
    diff_conn = ""
    diff_logic = """
  assign ws_valid          = 1'b0;
  assign debug0_wb_pc      = 32'b0;
  assign debug0_wb_rf_wen  = 4'b0;
  assign debug0_wb_rf_wnum = 5'b0;
  assign debug0_wb_rf_wdata= 32'b0;
  assign debug0_wb_inst    = 32'b0;
"""
    if enable_diffcommit:
        diff_decl = """
  wire [101:0] diffCommit;
  wire         diffCommitValid;
"""
        diff_conn = """
    .diffCommit      (diffCommit),
    .diffCommitValid (diffCommitValid),
    .EN_diffCommit   (diffCommitValid),
"""
        diff_logic = """
  assign ws_valid          = diffCommitValid;
  assign debug0_wb_pc      = diffCommit[101:70];
  assign debug0_wb_inst    = diffCommit[69:38];
  assign debug0_wb_rf_wen  = {4{diffCommit[37]}};
  assign debug0_wb_rf_wnum = diffCommit[36:32];
  assign debug0_wb_rf_wdata= diffCommit[31:0];
"""

    return f"""// Auto-generated by src/scripts/gen_axi_wrapper.py
// Do not edit this file manually.

module core_top
#(
  parameter TLBNUM   = 32,
  parameter START_PC = 32'h1c000000
)
(
    input           aclk,
    input           aresetn,
    input    [ 7:0] intrpt,
    // AXI interface
    // read request
    output   [ 3:0] arid,
    output   [31:0] araddr,
    output   [ 7:0] arlen,
    output   [ 2:0] arsize,
    output   [ 1:0] arburst,
    output   [ 1:0] arlock,
    output   [ 3:0] arcache,
    output   [ 2:0] arprot,
    output          arvalid,
    input           arready,
    // read back
    input    [ 3:0] rid,
    input    [31:0] rdata,
    input    [ 1:0] rresp,
    input           rlast,
    input           rvalid,
    output          rready,
    // write request
    output   [ 3:0] awid,
    output   [31:0] awaddr,
    output   [ 7:0] awlen,
    output   [ 2:0] awsize,
    output   [ 1:0] awburst,
    output   [ 1:0] awlock,
    output   [ 3:0] awcache,
    output   [ 2:0] awprot,
    output          awvalid,
    input           awready,
    // write data
    output   [ 3:0] wid,
    output   [31:0] wdata,
    output   [ 3:0] wstrb,
    output          wlast,
    output          wvalid,
    input           wready,
    // write back
    input    [ 3:0] bid,
    input    [ 1:0] bresp,
    input           bvalid,
    output          bready,

    // debug
    input           break_point,
    input           infor_flag,
    input  [ 4:0]   reg_num,
    output          ws_valid,
    output [31:0]   rf_rdata,

    output [31:0] debug0_wb_pc,
    output [ 3:0] debug0_wb_rf_wen,
    output [ 4:0] debug0_wb_rf_wnum,
    output [31:0] debug0_wb_rf_wdata,
    output [31:0] debug0_wb_inst
);

  wire        core_rdAddrValid;
  wire [44:0] core_rdAddr;
  wire        core_rdAddrRdy;
  wire        core_rdDataRdy;

  wire        core_wrAddrValid;
  wire [44:0] core_wrAddr;
  wire        core_wrAddrRdy;

  wire        core_wrDataValid;
  wire [36:0] core_wrData;
  wire        core_wrDataRdy;

  wire        core_wrRespRdy;

  wire [17:0] cpuToHost;
  wire        cpuToHostRdy;
  wire        cpuToHostValid;
  wire        cpuToHostValidRdy;

  wire        rdAddrValidRdy;
  wire        wrAddrValidRdy;
  wire        wrDataValidRdy;

  reg host_started;
  always @(posedge aclk) begin
    if (!aresetn) begin
      host_started <= 1'b0;
    end else if (!host_started && host_to_cpu_en) begin
      host_started <= 1'b1;
    end
  end

  wire host_to_cpu_en = !host_started && host_to_cpu_rdy;
  wire host_to_cpu_rdy;

  wire [34:0] core_rdData = {{rdata, rresp, rlast}};

{diff_decl}
  mkCoreAxiTop u_core (
    .CLK                (aclk),
    .RST_N              (aresetn),

    .hostToCpu_startpc  (START_PC),
    .EN_hostToCpu       (host_to_cpu_en),
    .RDY_hostToCpu      (host_to_cpu_rdy),

    .cpuToHost          (cpuToHost),
    .EN_cpuToHost       (cpuToHostRdy),
    .RDY_cpuToHost      (cpuToHostRdy),
    .cpuToHostValid     (cpuToHostValid),
    .RDY_cpuToHostValid (cpuToHostValidRdy),

    .axiMem_rdAddrValid (core_rdAddrValid),
    .RDY_axiMem_rdAddrValid (rdAddrValidRdy),
    .axiMem_rdAddr      (core_rdAddr),
    .EN_axiMem_rdAddr   (core_rdAddrValid && arready),
    .RDY_axiMem_rdAddr  (core_rdAddrRdy),

    .axiMem_rdData_d    (core_rdData),
    .EN_axiMem_rdData   (rvalid && core_rdDataRdy),
    .RDY_axiMem_rdData  (core_rdDataRdy),

    .axiMem_wrAddrValid (core_wrAddrValid),
    .RDY_axiMem_wrAddrValid (wrAddrValidRdy),
    .axiMem_wrAddr      (core_wrAddr),
    .EN_axiMem_wrAddr   (core_wrAddrValid && awready),
    .RDY_axiMem_wrAddr  (core_wrAddrRdy),

    .axiMem_wrDataValid (core_wrDataValid),
    .RDY_axiMem_wrDataValid (wrDataValidRdy),
    .axiMem_wrData      (core_wrData),
    .EN_axiMem_wrData   (core_wrDataValid && wready),
    .RDY_axiMem_wrData  (core_wrDataRdy),

    .axiMem_wrResp_r    (bresp),
    .EN_axiMem_wrResp   (bvalid && core_wrRespRdy),
    .RDY_axiMem_wrResp  (core_wrRespRdy){diff_conn}
  );

  // AxiReadAddr = {{addr[31:0], len[7:0], size[2:0], burst[1:0]}}
  assign arid    = 4'b0;
  assign araddr  = core_rdAddr[44:13];
  assign arlen   = core_rdAddr[12:5];
  assign arsize  = core_rdAddr[4:2];
  assign arburst = core_rdAddr[1:0];
  assign arlock  = 2'b0;
  assign arcache = 4'b0;
  assign arprot  = 3'b0;
  assign arvalid = core_rdAddrValid;
  assign rready  = core_rdDataRdy;

  // AxiWriteAddr = {{addr[31:0], len[7:0], size[2:0], burst[1:0]}}
  assign awid    = 4'b0;
  assign awaddr  = core_wrAddr[44:13];
  assign awlen   = core_wrAddr[12:5];
  assign awsize  = core_wrAddr[4:2];
  assign awburst = core_wrAddr[1:0];
  assign awlock  = 2'b0;
  assign awcache = 4'b0;
  assign awprot  = 3'b0;
  assign awvalid = core_wrAddrValid;

  // AxiWriteData = {{data[31:0], strb[3:0], last}}
  assign wid     = 4'b0;
  assign wdata   = core_wrData[36:5];
  assign wstrb   = core_wrData[4:1];
  assign wlast   = core_wrData[0];
  assign wvalid  = core_wrDataValid;

  assign bready  = core_wrRespRdy;

  // Keep interface compatible with chiplab mycpu template.
  assign rf_rdata = 32'b0;
{diff_logic}

  wire _unused_ok = &{{1'b0, rid, bid, break_point, infor_flag, reg_num, cpuToHost, cpuToHostValid,
                       core_rdAddrRdy, core_wrAddrRdy, core_wrDataRdy,
                       cpuToHostValidRdy, rdAddrValidRdy, wrAddrValidRdy, wrDataValidRdy}};

endmodule
"""


def main() -> None:
    root = repo_root()
    mk_core_axi_top_v = root / "src" / "build" / "verilog" / "mkCoreAxiTop.v"
    output_v = root / "chiplab" / "IP" / "myCPU" / "mycpu_top.v"

    if not mk_core_axi_top_v.exists():
        raise FileNotFoundError(f"Input not found: {mk_core_axi_top_v}")

    text = mk_core_axi_top_v.read_text(encoding="utf-8", errors="ignore")
    require_ports(
        text,
        [
            "module mkCoreAxiTop(",
            "axiMem_rdAddr",
            "axiMem_wrAddr",
            "axiMem_wrData",
            "axiMem_rdData_d",
            "axiMem_wrResp_r",
            "hostToCpu_startpc",
        ],
    )

    enable_diffcommit = "diffCommit" in text and "diffCommitValid" in text
    wrapper = render_wrapper(enable_diffcommit)
    output_v.write_text(wrapper, encoding="utf-8")

    print(f"Generated: {output_v}")
    print(f"DiffCommit debug bridge: {'enabled' if enable_diffcommit else 'disabled'}")


if __name__ == "__main__":
    main()
